#29012025

##Unit 2 : Linear algebra with python.

###Sublibrary of numpy for linear algebra : numpy.linalg

In [ ]:
import numpy.linalg as la
import numpy as np

##Basic Matrix Operations

Norm, Determinant, Eigenvalues, inverse

###Norm of a vector

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
la.norm(x)

16.881943016134134

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

###Rank of a matrix

In [ ]:
la.matrix_rank(x)

2

###Determinant of a matrix

In [ ]:
la.det(x)

0.0

Raise to power of a matrix

In [ ]:
la.matrix_power(x,10)

array([[132476037840, 162775103256, 193074168672],
       [300005963406, 368621393481, 437236823556],
       [467535888972, 574467683706, 681399478440]])

EigenValues and EigenVectors

In [ ]:
la.eig(x)[0] #EigenValues

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [ ]:
la.eig(x)[1] #EigenVectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Store em
[L, Q] = la.eig(x)

In [ ]:
#Check if we have the right values
x@Q[:,0] - L[0]*Q[:, 0]

array([ 4.88498131e-15, -1.77635684e-15, -1.77635684e-15])

In [ ]:
x@Q[:,1] - L[1]*Q[:, 1]

array([-2.22044605e-16, -7.35522754e-16, -1.55431223e-15])

In [ ]:
x@Q[:,2] - L[2]*Q[:, 2]

array([-4.11465368e-16, -2.06364913e-15,  3.65690749e-16])

In [ ]:
x@Q[:,2]

array([-9.43689571e-16, -9.99200722e-16, -1.66533454e-16])

In [ ]:
Q@(np.diag(L))@la.inv(Q) # x = QLQT

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
x = np.array([[1,0,1], [0,1,1], [1,1,0]])

In [ ]:
la.matrix_rank(x)

3

In [ ]:
la.inv(x)

array([[ 0.5, -0.5,  0.5],
       [-0.5,  0.5,  0.5],
       [ 0.5,  0.5, -0.5]])

In [ ]:
la.eig(x)

EigResult(eigenvalues=array([-1.,  1.,  2.]), eigenvectors=array([[ 4.08248290e-01, -7.07106781e-01, -5.77350269e-01],
       [ 4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
       [-8.16496581e-01, -1.19365036e-17, -5.77350269e-01]]))

In [ ]:
[L, Q] = la.eig(x)

In [ ]:
Q

array([[ 4.08248290e-01, -7.07106781e-01, -5.77350269e-01],
       [ 4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
       [-8.16496581e-01, -1.19365036e-17, -5.77350269e-01]])

In [ ]:
Q@np.diag(L)@Q.T

array([[1.00000000e+00, 2.22044605e-16, 1.00000000e+00],
       [2.22044605e-16, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [ ]:
Q.T@x@Q

array([[-1.00000000e+00, -9.74611434e-18,  1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  3.88578059e-16],
       [-1.11022302e-16,  3.46849994e-16,  2.00000000e+00]])

#Singular Value Decomposition

Let, A be a n*n matrix

Then,  A = UΣV^T,

where U_(m*m) is the eigenmatrix of AA^T

and where V_(n*n) is the eigenmatrix of A^TA

AA^T = UΛ_1U^T

A^TA = VΛ_2V^T

Σ_(mxn) = #"Check Notes"#

In [ ]:
la.svd(x)

SVDResult(U=array([[-5.77350269e-01,  4.08248290e-01, -7.07106781e-01],
       [-5.77350269e-01, -8.16496581e-01, -7.85046229e-17],
       [-5.77350269e-01,  4.08248290e-01,  7.07106781e-01]]), S=array([2., 1., 1.]), Vh=array([[-0.57735027, -0.57735027, -0.57735027],
       [ 0.81649658, -0.40824829, -0.40824829],
       [-0.        ,  0.70710678, -0.70710678]]))

In [ ]:
[U, S, V] = la.svd(x)

In [ ]:
U

array([[-5.77350269e-01,  4.08248290e-01, -7.07106781e-01],
       [-5.77350269e-01, -8.16496581e-01, -7.85046229e-17],
       [-5.77350269e-01,  4.08248290e-01,  7.07106781e-01]])

In [ ]:
S

array([2., 1., 1.])

In [ ]:
V

array([[-0.57735027, -0.57735027, -0.57735027],
       [ 0.81649658, -0.40824829, -0.40824829],
       [-0.        ,  0.70710678, -0.70710678]])

In [ ]:
la.eig(x@x.transpose())[1]

array([[-0.81649658,  0.57735027, -0.32444284],
       [ 0.40824829,  0.57735027, -0.48666426],
       [ 0.40824829,  0.57735027,  0.81110711]])

###Solve system of Equations

In [ ]:
la.solve(x, np.array([1,2,3]))

array([ 1.,  2., -0.])

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
la.lstsq(x, np.array([1,2,1]), rcond = -1)

(array([-6.66666667e-01,  2.22044605e-16,  6.66666667e-01]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))

###Row Reduced Echelon Form

In [ ]:
import numpy as np

def rref(matrix):
    matrix = np.array(matrix, dtype=float)  # Convert to float for accurate calculations

    rows, cols = matrix.shape
    lead = 0

    for r in range(rows):
        if lead >= cols:
            break
        i = r

        while matrix[i, lead] == 0:
            i += 1
            if i == rows:
                i = r
                lead += 1
                if cols == lead:
                    return matrix
        matrix[[i, r]] = matrix[[r, i]]  # Swap rows

        if matrix[r, lead] != 0:
            matrix[r] = matrix[r] / matrix[r, lead]  # Normalize row

        for i in range(rows):
            if i != r:
                factor = matrix[i, lead]
                matrix[i] = matrix[i] - factor * matrix[r]  # Eliminate other rows

        lead += 1

    return matrix

In [ ]:
rref(x)

array([[ 1.,  0., -1.],
       [-0.,  1.,  2.],
       [ 0.,  0.,  0.]])

#LU Decomposition

In [1]:
#See Notes

#03020225

In [2]:
import numpy as np
import numpy.linalg as la

In [4]:
A = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [6]:
#Pseduo Inverse of a matrix
la.pinv(A)

array([[-0.48333333, -0.24444444, -0.00555556,  0.23333333],
       [-0.03333333, -0.01111111,  0.01111111,  0.03333333],
       [ 0.41666667,  0.22222222,  0.02777778, -0.16666667]])

In [9]:
#QR Decomposition
la.qr(A)

QRResult(Q=array([[-0.07761505, -0.83305216,  0.54563501],
       [-0.31046021, -0.45123659, -0.69190406],
       [-0.54330537, -0.06942101, -0.2530969 ],
       [-0.77615053,  0.31239456,  0.39936595]]), R=array([[-1.28840987e+01, -1.45916299e+01, -1.62991610e+01],
       [ 0.00000000e+00, -1.04131520e+00, -2.08263040e+00],
       [ 0.00000000e+00,  0.00000000e+00, -6.31169357e-15]]))

In [10]:
[Q, R] = la.qr(A)

In [11]:
Q #4x3

array([[-0.07761505, -0.83305216,  0.54563501],
       [-0.31046021, -0.45123659, -0.69190406],
       [-0.54330537, -0.06942101, -0.2530969 ],
       [-0.77615053,  0.31239456,  0.39936595]])

In [12]:
R #3x3

array([[-1.28840987e+01, -1.45916299e+01, -1.62991610e+01],
       [ 0.00000000e+00, -1.04131520e+00, -2.08263040e+00],
       [ 0.00000000e+00,  0.00000000e+00, -6.31169357e-15]])

In [15]:
Q@R

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [9]:
import numpy as np
import numpy.linalg as la
la.eig([[2,-2,-4],[-1,3,4], [1,-2,-3]])

EigResult(eigenvalues=array([9.64372082e-16, 1.00000000e+00, 1.00000000e+00]), eigenvectors=array([[ 0.57735027,  0.3867268 , -0.87863096],
       [-0.57735027, -0.78252864,  0.30140083],
       [ 0.57735027,  0.48794602, -0.37035816]]))

In [11]:
la.eig([[2,-2,-4],[-1,3,4], [1,-2,-3]])[1][:, np.argmin(la.eig([[2,-2,-4],[-1,3,4], [1,-2,-3]])[0])].T @ np.array([[2,-2,-4],[-1,3,4], [1,-2,-3]]) @ la.eig([[2,-2,-4],[-1,3,4], [1,-2,-3]])[1][:, np.argmin(la.eig([[2,-2,-4],[-1,3,4], [1,-2,-3]])[0])]

-4.440892098500626e-16